CREATE TABLE PEOPLES (
    ID VARCHAR(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    PHONE_NUMBER VARCHAR(15) NOT NULL
);

CREATE TABLE BOOKS (
    ID VARCHAR(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    DESCRIPTION VARCHAR(4200)
);

CREATE TABLE BOOKS_RENTALS (
    ID VARCHAR(10) NOT NULL PRIMARY KEY,
    BOOK_ID VARCHAR(10),
    PEOPLE_ID VARCHAR(10) NULL,
    RENTED_DATE DATETIME DEFAULT NOW(),
    FOREIGN KEY (BOOK_ID)
        REFERENCES BOOKS (ID)
        ON DELETE CASCADE,
    FOREIGN KEY (PEOPLE_ID)
        REFERENCES PEOPLES (ID)
        ON DELETE CASCADE
);
