DELIMITER $$
	CREATE PROCEDURE RENT_BOOK(IN _BOOK_ID VARCHAR(10), _PEOPLE_ID VARCHAR(10))
		BEGIN
			DECLARE BOOKS_RENTALS_ID VARCHAR(10);
				SET BOOKS_RENTALS_ID = (SELECT ID FROM BOOKS_RENTALS WHERE BOOK_ID = _BOOK_ID);
				UPDATE BOOKS_RENTALS SET PEOPLE_ID = _PEOPLE_ID WHERE ID = BOOKS_RENTALS_ID;
		END $$
DELIMITER ;
