DELIMITER $$
	CREATE PROCEDURE CREATE_BOOK(IN _BOOK_ID VARCHAR(10), IN _BOOKS_RENTALS_ID VARCHAR(10), IN _NAME VARCHAR(120), IN _DESCRIPTION VARCHAR(4200))
		BEGIN
			INSERT INTO BOOKS(ID, NAME, DESCRIPTION) VALUES (_ID, _NAME, _DESCRIPTION);
			INSERT INTO BOOKS_RENTALS(ID, BOOK_ID) VALUES (_BOOKS_RENTALS_ID, _BOOK_ID);
		END $$
DELIMITER ;

DELIMITER $$
	CREATE PROCEDURE UPDATE_BOOK(IN _ID VARCHAR(10), IN _NAME VARCHAR(120), IN _DESCRIPTION VARCHAR(4200))
		BEGIN
			UPDATE BOOKS SET NAME = _NAME, DESCRIPTION = _DESCRIPTION WHERE ID = _ID;
		END $$
DELIMITER ;

DELIMITER $$
	CREATE PROCEDURE DELETE_BOOK(IN _ID VARCHAR(10))
		BEGIN
			DELETE FROM BOOKS WHERE ID = _ID;
		END $$
DELIMITER ;
