CREATE VIEW VW_BOOKS_RENTED AS
    SELECT 
        BOOKS.ID AS BOOK_ID,
        BOOKS.NAME AS BOOK_NAME,
        PEOPLES.NAME AS PEOPLE_RENTED,
        BOOKS_RENTALS.RENTED_DATE AS RENTED_DATE
    FROM
        BOOKS
            INNER JOIN
        BOOKS_RENTALS ON BOOKS.ID = BOOKS_RENTALS.BOOK_ID
            INNER JOIN
        PEOPLES ON BOOKS_RENTALS.PEOPLE_ID = PEOPLES.ID;

CREATE VIEW VW_BOOKS_NOT_RENTED AS
    SELECT 
        BOOKS.ID AS BOOK_ID,
        BOOKS.NAME AS BOOK_NAME,
        BOOKS_RENTALS.RENTED_DATE AS LAST_RENTED_DATE
    FROM
        BOOKS_RENTALS
            INNER JOIN
        BOOKS ON BOOKS_RENTALS.BOOK_ID = BOOKS.ID
    WHERE
        ISNULL(BOOKS_RENTALS.PEOPLE_ID);
